# Generated by Django 3.0 on 2020-01-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0008_auto_20200113_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='comment_acces',
            field=models.BooleanField(default=False),
        ),
    ]
