# Generated by Django 3.0.2 on 2020-01-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
