# Generated by Django 3.0.2 on 2020-01-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200117_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
