# Generated by Django 3.0.2 on 2020-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20200117_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='create_date1',
        ),
        migrations.RemoveField(
            model_name='file',
            name='create_date2',
        ),
        migrations.AlterField(
            model_name='file',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
