# Generated by Django 3.0 on 2020-01-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20200117_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
